### ISSUE TITLE
ErrorException: syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by anibalsanchez** [zero-24/plg_system_force2fausergroup#4]
Hi,

This error has been reported in the server:

```php
ErrorException: syntax error, unexpected ':', expecting ';' or '{'
  File "plugins/system/force2fausergroup/force2fausergroup.php", line 86, in handleFatalError
    private function isTwoFactorAuthenticationRequired(): bool
```

**Comment by anibalsanchez** [comment]
runtime = php 5.6.40
It looks like a server problem.... at some time it executed on php 5.6.40

**Comment by anibalsanchez** [comment]
It was a server issue.

**Comment by zero-24** [comment]
yes php Minimum is 7.2.5 that plugin should not install on PHP5.6 any more.

**Comment by anibalsanchez** [comment]
We think that cPanel executes PHP 5.6 some times since it was the default PHP env. We've changed the default env to PHP 7.2. Let's see if the change fixes the issue.

**Comment by zero-24** [comment]
👍
